# Generated by Django 3.2.5 on 2021-07-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_detail',
            old_name='langauge',
            new_name='language',
        ),
    ]
